# Generated by Django 3.2.3 on 2022-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='accepted_status',
            field=models.BooleanField(default=False),
        ),
    ]
