# Generated by Django 3.2.3 on 2021-06-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20210609_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststring',
            name='string',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
