# Generated by Django 3.2.3 on 2022-04-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='user',
        ),
    ]
