# Generated by Django 3.2.3 on 2021-06-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='test_string',
        ),
        migrations.AddField(
            model_name='entry',
            name='test_strings',
            field=models.ManyToManyField(to='entries.TestString'),
        ),
    ]
